name: pxc

releases:
- name: pxc
  version: "0.21.5"
  url: "http://paas-lab-minio.uk.fid-intl.com:9001/bosh-artifacts/releases/pxc-release-0.21.5.tgz"
  sha1: "a3a46bba81e94e650fda35f85cd3da0ae1264178"
- name: bpm
  url: "http://paas-lab-minio.uk.fid-intl.com:9001/bosh-artifacts/releases/bpm-1.1.0-ubuntu-xenial-315.36-20190610-155244-17035177-20190610155251.tgz"
  version: latest

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: mysql
  instances: 1
  azs: [z1, z2, z3]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  persistent_disk: 10000
  jobs:
  - name: pxc-mysql
    release: pxc
    properties:
      admin_password: ((cf_mysql_mysql_admin_password))
      tls:
        galera: ((galera_server_certificate))
        server: ((mysql_server_certificate))
  - name: smoke-tests
    release: pxc
    properties:
      db_password: ((smoke_tests_db_password))
  - name: smoke-tests-user
    release: pxc

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1
  canary_watch_time: 10000-600000
  max_in_flight: 1
  update_watch_time: 10000-600000

variables:
- name: cf_mysql_mysql_admin_password
  type: password
- name: pxc_galera_ca
  type: certificate
  options:
    is_ca: true
    common_name: pxc_galera_ca
- name: pxc_server_ca
  type: certificate
  options:
    is_ca: true
    common_name: pxc_server_ca
- name: galera_server_certificate
  type: certificate
  options:
    ca: pxc_galera_ca
    extended_key_usage: [ "server_auth", "client_auth" ]
    common_name: galera_server_certificate
- name: mysql_server_certificate
  type: certificate
  options:
    ca: pxc_server_ca
    common_name: mysql_server_certificate
- name: smoke_tests_db_password
  type: password
